-- ---------------------------------------------------------------------------
-- 0014 — Brändiluettelon siemenaineisto
-- ---------------------------------------------------------------------------
--
-- GENEROITU TIEDOSTO. Älä muokkaa käsin.
--   node scripts/merchant-seed.mjs > supabase/migrations/0014_merchant_seed.sql
--
-- Aliakset on normalisoitu samalla säännöllä jota tunnistus käyttää.
-- Käsin kirjoitettuina ne ajautuisivat erilleen, ja kauppa jäisi
-- tunnistamatta ilman että kukaan huomaisi miksi.
--
-- Uusi yritys lisätään skriptiin ja migraatio ajetaan uudelleen.
-- Käyttöliittymään ei kosketa.

insert into merchants (id, name, category, brand_color, brand_background, logo_url) values
  ('k-market', 'K-Market', 'grocery', '#F28C28', '#FFF7ED', '/kaupat/k-market.png'),
  ('k-supermarket', 'K-Supermarket', 'grocery', '#E85D04', '#FFF7ED', null),
  ('k-citymarket', 'K-Citymarket', 'grocery', '#D64500', '#FFF7ED', '/kaupat/k-citymarket.png'),
  ('s-market', 'S-market', 'grocery', '#00AA46', '#F0FDF4', '/kaupat/s-market.png'),
  ('alepa', 'Alepa', 'grocery', '#E30613', '#FFF1F2', '/kaupat/alepa.png'),
  ('sale', 'Sale', 'grocery', '#0A7D33', '#F0FDF4', null),
  ('prisma', 'Prisma', 'grocery', '#00693E', '#F0FDF4', '/kaupat/prisma.png'),
  ('lidl', 'Lidl', 'grocery', '#0050AA', '#EFF6FF', '/kaupat/lidl.png'),
  ('minimani', 'Minimani', 'grocery', '#C8102E', '#FFF1F2', null),
  ('gigantti', 'Gigantti', 'electronics', '#005EB8', '#EFF6FF', null),
  ('power', 'POWER', 'electronics', '#0F172A', '#F1F5F9', null),
  ('verkkokauppa-com', 'Verkkokauppa.com', 'electronics', '#E4002B', '#FFF1F2', null),
  ('elisa', 'Elisa', 'electronics', '#0019AF', '#EFF6FF', null),
  ('dna', 'DNA', 'electronics', '#6E2585', '#FAF5FF', null),
  ('telia', 'Telia', 'electronics', '#990AE3', '#FAF5FF', null),
  ('k-rauta', 'K-Rauta', 'hardware', '#E85D04', '#FFF7ED', '/kaupat/k-rauta.png'),
  ('bauhaus', 'BAUHAUS', 'hardware', '#C8102E', '#FFF1F2', '/kaupat/bauhaus.png'),
  ('stark', 'STARK', 'hardware', '#1D4ED8', '#EFF6FF', null),
  ('puuilo', 'Puuilo', 'hardware', '#F59E0B', '#FFFBEB', null),
  ('motonet', 'Motonet', 'automotive', '#0F52BA', '#EFF6FF', null),
  ('neste', 'Neste', 'automotive', '#003F87', '#EFF6FF', '/kaupat/neste.png'),
  ('tokmanni', 'Tokmanni', 'retail', '#E4002B', '#FFF1F2', null),
  ('clas-ohlson', 'Clas Ohlson', 'retail', '#00447C', '#EFF6FF', null),
  ('ikea', 'IKEA', 'retail', '#0058A3', '#EFF6FF', null),
  ('yliopiston-apteekki', 'Yliopiston Apteekki', 'pharmacy', '#00843D', '#F0FDF4', null),
  ('alko', 'Alko', 'alcohol', '#003DA5', '#EFF6FF', '/kaupat/alko.png'),
  ('mcdonalds', 'McDonald''s', 'restaurant', '#DA291C', '#FFF1F2', null),
  ('hesburger', 'Hesburger', 'restaurant', '#004B93', '#EFF6FF', null),
  ('burger-king', 'Burger King', 'restaurant', '#D62300', '#FFF7ED', null),
  ('subway', 'Subway', 'restaurant', '#008C15', '#F0FDF4', null),
  ('wolt', 'Wolt', 'restaurant', '#00C2E8', '#ECFEFF', null),
  ('foodora', 'Foodora', 'restaurant', '#D70F64', '#FDF2F8', null),
  ('hsl', 'HSL', 'transport', '#007AC9', '#EFF6FF', null),
  ('vr', 'VR', 'transport', '#007A3D', '#F0FDF4', null),
  ('finnair', 'Finnair', 'transport', '#0B1560', '#EFF6FF', null),
  ('kespro', 'Kespro', 'grocery', '#E85D04', '#FFF7ED', '/kaupat/kespro.png'),
  ('metro-tukku', 'Metro-tukku', 'grocery', '#00519E', '#EFF6FF', null),
  ('valio', 'Valio', 'grocery', '#0057B8', '#EFF6FF', null),
  ('heinon-tukku', 'Heinon Tukku', 'grocery', '#C8102E', '#FFF1F2', null)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  brand_color = excluded.brand_color,
  brand_background = excluded.brand_background,
  logo_url = excluded.logo_url,
  updated_at = now();

insert into merchant_aliases (merchant_id, alias) values
  ('k-market', 'k market'),
  ('k-market', 'kmarket'),
  ('k-supermarket', 'k supermarket'),
  ('k-supermarket', 'ksupermarket'),
  ('k-citymarket', 'k citymarket'),
  ('k-citymarket', 'citymarket'),
  ('s-market', 's market'),
  ('s-market', 'smarket'),
  ('alepa', 'alepa'),
  ('sale', 'sale'),
  ('prisma', 'prisma'),
  ('lidl', 'lidl'),
  ('minimani', 'minimani'),
  ('gigantti', 'gigantti'),
  ('power', 'power'),
  ('verkkokauppa-com', 'verkkokauppa.com'),
  ('verkkokauppa-com', 'verkkokauppa com'),
  ('verkkokauppa-com', 'verkkokauppa'),
  ('elisa', 'elisa'),
  ('dna', 'dna'),
  ('telia', 'telia'),
  ('k-rauta', 'k rauta'),
  ('k-rauta', 'krauta'),
  ('bauhaus', 'bauhaus'),
  ('stark', 'stark'),
  ('puuilo', 'puuilo'),
  ('motonet', 'motonet'),
  ('neste', 'neste'),
  ('neste', 'neste k'),
  ('neste', 'neste express'),
  ('neste', 'neste oil'),
  ('tokmanni', 'tokmanni'),
  ('clas-ohlson', 'clas ohlson'),
  ('ikea', 'ikea'),
  ('yliopiston-apteekki', 'yliopiston apteekki'),
  ('yliopiston-apteekki', 'ya apteekki'),
  ('alko', 'alko'),
  ('mcdonalds', 'mcdonald s'),
  ('mcdonalds', 'mcdonalds'),
  ('mcdonalds', 'mc donalds'),
  ('hesburger', 'hesburger'),
  ('burger-king', 'burger king'),
  ('subway', 'subway'),
  ('wolt', 'wolt'),
  ('wolt', 'wolt enterprises'),
  ('foodora', 'foodora'),
  ('hsl', 'hsl'),
  ('hsl', 'helsingin seudun liikenne'),
  ('vr', 'vr'),
  ('vr', 'vr group'),
  ('finnair', 'finnair'),
  ('kespro', 'kespro'),
  ('metro-tukku', 'metro tukku'),
  ('metro-tukku', 'meira nova'),
  ('valio', 'valio'),
  ('heinon-tukku', 'heinon tukku')
on conflict (alias) do update set merchant_id = excluded.merchant_id;

