-- ---------------------------------------------------------------------------
-- 0014 — Brändiluettelon siemenaineisto
-- ---------------------------------------------------------------------------
--
-- GENEROITU TIEDOSTO. Älä muokkaa käsin.
--   node scripts/merchant-seed.mjs > supabase/migrations/0014_merchant_seed.sql
--
-- Aliakset on normalisoitu samalla säännöllä jota tunnistus käyttää.
-- Käsin kirjoitettuina ne ajautuisivat erilleen, ja kauppa jäisi
-- tunnistamatta ilman että kukaan huomaisi miksi.
--
-- Uusi yritys lisätään skriptiin ja migraatio ajetaan uudelleen.
-- Käyttöliittymään ei kosketa.

insert into merchants (id, name, category, brand_color, brand_background, logo_url) values
  ('k-market', 'K-Market', 'grocery', '#F28C28', '#FFF7ED', '/kaupat/k-market.png'),
  ('k-supermarket', 'K-Supermarket', 'grocery', '#E85D04', '#FFF7ED', '/kaupat/k-supermarket.png'),
  ('k-citymarket', 'K-Citymarket', 'grocery', '#D64500', '#FFF7ED', '/kaupat/k-citymarket.png'),
  ('s-market', 'S-market', 'grocery', '#00AA46', '#F0FDF4', '/kaupat/s-market.png'),
  ('alepa', 'Alepa', 'grocery', '#E30613', '#FFF1F2', '/kaupat/alepa.png'),
  ('sale', 'Sale', 'grocery', '#0A7D33', '#F0FDF4', null),
  ('prisma', 'Prisma', 'grocery', '#00693E', '#F0FDF4', '/kaupat/prisma.png'),
  ('lidl', 'Lidl', 'grocery', '#0050AA', '#EFF6FF', '/kaupat/lidl.png'),
  ('minimani', 'Minimani', 'grocery', '#C8102E', '#FFF1F2', '/kaupat/minimani.png'),
  ('sokos', 'Sokos', 'retail', '#1B2A4A', '#EEF2F7', '/kaupat/sokos.png'),
  ('gigantti', 'Gigantti', 'electronics', '#005EB8', '#EFF6FF', '/kaupat/gigantti.png'),
  ('power', 'POWER', 'electronics', '#0F172A', '#F1F5F9', '/kaupat/power.png'),
  ('verkkokauppa-com', 'Verkkokauppa.com', 'electronics', '#E4002B', '#FFF1F2', '/kaupat/verkkokauppa-com.png'),
  ('elisa', 'Elisa', 'electronics', '#0019AF', '#EFF6FF', '/kaupat/elisa.png'),
  ('dna', 'DNA', 'electronics', '#6E2585', '#FAF5FF', '/kaupat/dna.png'),
  ('telia', 'Telia', 'electronics', '#990AE3', '#FAF5FF', '/kaupat/telia.png'),
  ('k-rauta', 'K-Rauta', 'hardware', '#E85D04', '#FFF7ED', '/kaupat/k-rauta.png'),
  ('bauhaus', 'BAUHAUS', 'hardware', '#C8102E', '#FFF1F2', '/kaupat/bauhaus.png'),
  ('stark', 'STARK', 'hardware', '#1D4ED8', '#EFF6FF', '/kaupat/stark.png'),
  ('puuilo', 'Puuilo', 'hardware', '#F59E0B', '#FFFBEB', '/kaupat/puuilo.png'),
  ('byggmax', 'Byggmax', 'hardware', '#E4002B', '#FFF1F2', '/kaupat/byggmax.png'),
  ('biltema', 'Biltema', 'hardware', '#0072CE', '#EFF6FF', '/kaupat/biltema.png'),
  ('motonet', 'Motonet', 'automotive', '#0F52BA', '#EFF6FF', '/kaupat/motonet.png'),
  ('neste', 'Neste', 'automotive', '#003F87', '#EFF6FF', '/kaupat/neste.png'),
  ('abc', 'ABC', 'automotive', '#B07B00', '#FFFBEB', '/kaupat/abc.png'),
  ('st1', 'St1', 'automotive', '#E30613', '#FFF1F2', '/kaupat/st1.png'),
  ('teboil', 'Teboil', 'automotive', '#E1001A', '#FFF1F2', '/kaupat/teboil.png'),
  ('tokmanni', 'Tokmanni', 'retail', '#E4002B', '#FFF1F2', '/kaupat/tokmanni.png'),
  ('clas-ohlson', 'Clas Ohlson', 'retail', '#00447C', '#EFF6FF', '/kaupat/clas-ohlson.png'),
  ('ikea', 'IKEA', 'retail', '#0058A3', '#EFF6FF', '/kaupat/ikea.png'),
  ('jysk', 'JYSK', 'retail', '#1A3B7C', '#EFF6FF', '/kaupat/jysk.png'),
  ('sinsay', 'Sinsay', 'retail', '#111111', '#F4F4F5', '/kaupat/sinsay.png'),
  ('xxl', 'XXL', 'retail', '#6D9A00', '#F7FEE7', '/kaupat/xxl.png'),
  ('intersport', 'Intersport', 'retail', '#00539F', '#EFF6FF', '/kaupat/intersport.png'),
  ('r-kioski', 'R-kioski', 'retail', '#0072CE', '#EFF6FF', '/kaupat/r-kioski.png'),
  ('yliopiston-apteekki', 'Yliopiston Apteekki', 'pharmacy', '#00843D', '#F0FDF4', '/kaupat/yliopiston-apteekki.png'),
  ('alko', 'Alko', 'alcohol', '#003DA5', '#EFF6FF', '/kaupat/alko.png'),
  ('mcdonalds', 'McDonald''s', 'restaurant', '#DA291C', '#FFF1F2', '/kaupat/mcdonalds.png'),
  ('hesburger', 'Hesburger', 'restaurant', '#004B93', '#EFF6FF', '/kaupat/hesburger.png'),
  ('burger-king', 'Burger King', 'restaurant', '#D62300', '#FFF7ED', '/kaupat/burger-king.png'),
  ('subway', 'Subway', 'restaurant', '#008C15', '#F0FDF4', '/kaupat/subway.png'),
  ('wolt', 'Wolt', 'restaurant', '#00C2E8', '#ECFEFF', '/kaupat/wolt.png'),
  ('foodora', 'Foodora', 'restaurant', '#D70F64', '#FDF2F8', '/kaupat/foodora.png'),
  ('helmi-simpukka', 'Helmi Simpukka', 'restaurant', '#00463C', '#ECFDF5', '/kaupat/helmi-simpukka.png'),
  ('kotipizza', 'Kotipizza', 'restaurant', '#00693E', '#F0FDF4', '/kaupat/kotipizza.png'),
  ('hsl', 'HSL', 'transport', '#007AC9', '#EFF6FF', '/kaupat/hsl.png'),
  ('vr', 'VR', 'transport', '#007A3D', '#F0FDF4', '/kaupat/vr.png'),
  ('finnair', 'Finnair', 'transport', '#0B1560', '#EFF6FF', null),
  ('kespro', 'Kespro', 'grocery', '#E85D04', '#FFF7ED', '/kaupat/kespro.png'),
  ('metro-tukku', 'Metro-tukku', 'grocery', '#00519E', '#EFF6FF', '/kaupat/metro-tukku.png'),
  ('valio', 'Valio', 'grocery', '#0057B8', '#EFF6FF', '/kaupat/valio.png'),
  ('meira-nova', 'Meira Nova', 'grocery', '#00843D', '#F0FDF4', '/kaupat/meira-nova.png'),
  ('atria', 'Atria', 'grocery', '#C8102E', '#FFF1F2', '/kaupat/atria.png'),
  ('hartwall', 'Hartwall', 'grocery', '#1B2A6B', '#EEF2FF', '/kaupat/hartwall.png'),
  ('posti', 'Posti', 'services', '#E85D04', '#FFF7ED', '/kaupat/posti.png'),
  ('heinon-tukku', 'Heinon Tukku', 'grocery', '#C8102E', '#FFF1F2', null)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  brand_color = excluded.brand_color,
  brand_background = excluded.brand_background,
  logo_url = excluded.logo_url,
  updated_at = now();

insert into merchant_aliases (merchant_id, alias) values
  ('k-market', 'k market'),
  ('k-market', 'kmarket'),
  ('k-supermarket', 'k supermarket'),
  ('k-supermarket', 'ksupermarket'),
  ('k-citymarket', 'k citymarket'),
  ('k-citymarket', 'citymarket'),
  ('s-market', 's market'),
  ('s-market', 'smarket'),
  ('alepa', 'alepa'),
  ('sale', 'sale'),
  ('prisma', 'prisma'),
  ('lidl', 'lidl'),
  ('minimani', 'minimani'),
  ('sokos', 'sokos'),
  ('gigantti', 'gigantti'),
  ('power', 'power'),
  ('verkkokauppa-com', 'verkkokauppa.com'),
  ('verkkokauppa-com', 'verkkokauppa com'),
  ('verkkokauppa-com', 'verkkokauppa'),
  ('elisa', 'elisa'),
  ('dna', 'dna'),
  ('telia', 'telia'),
  ('k-rauta', 'k rauta'),
  ('k-rauta', 'krauta'),
  ('bauhaus', 'bauhaus'),
  ('stark', 'stark'),
  ('puuilo', 'puuilo'),
  ('byggmax', 'byggmax'),
  ('biltema', 'biltema'),
  ('motonet', 'motonet'),
  ('neste', 'neste'),
  ('neste', 'neste k'),
  ('neste', 'neste express'),
  ('neste', 'neste oil'),
  ('abc', 'abc'),
  ('abc', 'abc asema'),
  ('abc', 'abc liikennemyymälä'),
  ('st1', 'st1'),
  ('st1', 'st 1'),
  ('teboil', 'teboil'),
  ('tokmanni', 'tokmanni'),
  ('clas-ohlson', 'clas ohlson'),
  ('ikea', 'ikea'),
  ('jysk', 'jysk'),
  ('sinsay', 'sinsay'),
  ('xxl', 'xxl'),
  ('xxl', 'xxl sport'),
  ('xxl', 'xxl sports'),
  ('intersport', 'intersport'),
  ('r-kioski', 'r kioski'),
  ('r-kioski', 'rkioski'),
  ('yliopiston-apteekki', 'yliopiston apteekki'),
  ('yliopiston-apteekki', 'ya apteekki'),
  ('alko', 'alko'),
  ('mcdonalds', 'mcdonald s'),
  ('mcdonalds', 'mcdonalds'),
  ('mcdonalds', 'mc donalds'),
  ('hesburger', 'hesburger'),
  ('burger-king', 'burger king'),
  ('subway', 'subway'),
  ('wolt', 'wolt'),
  ('wolt', 'wolt enterprises'),
  ('foodora', 'foodora'),
  ('helmi-simpukka', 'helmi simpukka'),
  ('helmi-simpukka', 'helmisimpukka'),
  ('kotipizza', 'kotipizza'),
  ('hsl', 'hsl'),
  ('hsl', 'helsingin seudun liikenne'),
  ('vr', 'vr'),
  ('vr', 'vr group'),
  ('finnair', 'finnair'),
  ('kespro', 'kespro'),
  ('metro-tukku', 'metro tukku'),
  ('valio', 'valio'),
  ('meira-nova', 'meira nova'),
  ('meira-nova', 'meiranova'),
  ('atria', 'atria'),
  ('hartwall', 'hartwall'),
  ('posti', 'posti'),
  ('posti', 'posti group'),
  ('heinon-tukku', 'heinon tukku')
on conflict (alias) do update set merchant_id = excluded.merchant_id;

